image:
  file: Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

ports:
  - port: 8080
    onOpen: ignore
  - port: 5555
    onOpen: ignore
